sudo: required
services:
  - docker
matrix:
  include:
    - language: go
      go:
        - 1.11
      env:
        global:
          - CGO_ENABLED=0 GOOS=linux GOARCH=amd64    
        matrix:
          - SERVICE=events-service
          - SERVICE=booking-service
      before_install:
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - version=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt); curl -LO https://storage.googleapis.com/kubernetes-release/release/${version}/bin/linux/amd64/kubectl && chmod +x kubectl
      install:
        - dep ensure
        - echo "${KUBE_CA_CERT}" > ./ca.crt
        - ./kubectl config set-credentials travis-ci --token="${KUBE_TOKEN}"
        - ./kubectl config set-cluster "${KUBE_CLUSTER}" --server="${KUBE_SERVER}" --certificate-authority=ca.crt
        - ./kubectl config set-context "${KUBE_CLUSTER}" --cluster="${KUBE_CLUSTER}" --user=travis-ci --namespace=default
        - ./kubectl config use-context "${KUBE_CLUSTER}"
      scripts:
        - go vet $(go list ./... | grep -v vendor)
        - cd $SERVICE && go build
        - docker image build -t maxsuelmarinho/my-events:$SERVICE-$TRAVIS_BRANCH $SERVICE
      after_success:
        - if [ -n "${TRAVIS_TAG}" ]; then
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
            docker push maxsuelmarinho/my-events:$SERVICE-$TRAVIS_BRANCH;
            ./kubectl set image deployment/${SERVICE} api=maxsuelmarinho/my-events:$SERVICE-$TRAVIS_BRANCH;
          fi
