version: '3.1'
services:
  events-service:
    build: events-service/
    image: maxsuelmarinho/my-events:events-service-0.1
    ports:
      - "8181:8181"
    links:
      - mongodb
      - rabbitmq
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongo/data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null

  # management UI:
  # user: guest
  # pass: guest
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    ports:
      - "5617:5617"
      - "15672:15672" # management UI