version: '3.1'
services:
  events-service:
    build: events-service/
    image: maxsuelmarinho/my-events:events-service-0.1
    ports:
      - "8181:8181"
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongo/data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null