version: '3.1'
networks:
  my-events:
  monitoring:
  vcs:

volumes:
  prometheus-data:
  grafana-data:
  gitlab-config:
  gitlab-data:
  gitlab-logs:

secrets:
  gitlab_root_password:
    file: ./gitlab/root_password.txt

services:
  gitlab:
    build: gitlab/
    image: maxsuelmarinho/my-events:gitlab-0.1
    #image: gitlab/gitlab-ce:9.1.1-ce.0
    #image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: "peon"
    environment:
      #GITLAB_ROOT_PASSWORD: "g1tl4bs3cr3t"
      GITLAB_PRIVATE_TOKEN: "my-own-token"
      GITLAB_GROUP_NAME: "my-events"
      GITLAB_REPO_NAME: "my-events"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://peon:30080'
        gitlab_rails['gitlab_shell_ssh_port'] = 30022
        gitlab_rails['initial_root_password'] = File.read('/run/secrets/gitlab_root_password')
    secrets:
      - gitlab_root_password
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
    ports:
      - "30080:30080"
      - "30022:30022"
    networks:
      - vcs

  gitlab-runner:
    image: gitlab/gitlab-runner:v1.11.4
    container_name: gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitlab
    links:
      - gitlab
    networks:
      - vcs

  # UI: http://localhost:9090
  prometheus:
    image: prom/prometheus:v1.6.1
    container_name: "prometheus"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
     - monitoring
     - my-events

  # Default credentials:
  # username: admin
  # password: admin
  grafana:
    image: grafana/grafana:4.2.0
    container_name: "grafana"
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

  # management UI:
  # user: guest
  # pass: guest
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672" # management UI
    networks:
      - my-events

  kafka:
    image: spotify/kafka
    container_name: "kafka"
    ports:
      - "9092:9092"
    networks:
      - my-events

  event-db:
    image: mongo:latest
    container_name: "events-db"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    #volumes:
    #  - ./mongo/events/data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null
    networks:
      - my-events

  event-service:
    build:
      context: events-service/
      dockerfile: Dockerfile.scratch
    image: maxsuelmarinho/my-events:events-service-0.1
    ports:
      - "8181:8181"
      - "18181:18181"
    depends_on:
      - event-db
      - rabbitmq
    environment:
      AMQP_BROKER_URL: "amqp://guest:guest@rabbitmq:5672/"
      MONGO_URL: "mongodb://events-db/events"
      LISTEN_URL: "0.0.0.0:8181"
    networks:
      - my-events

  booking-service:
    build: booking-service/
    image: maxsuelmarinho/my-events:booking-service-0.1
    ports:
      - "8282:8282"
      - "18282:18282"
    depends_on:
      - booking-db
      - rabbitmq
    environment:
      AMQP_BROKER_URL: "amqp://guest:guest@rabbitmq:5672/"
      MONGO_URL: "mongodb://booking-db/bookings"
    networks:
      - my-events

  booking-db:
    image: mongo:latest
    container_name: "booking-db"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    #volumes:
    #  - ./mongo/booking/data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null
    networks:
      - my-events

  frontend:
    build: myevents-frontend/
    image: maxsuelmarinho/my-events:frontend-0.4
    ports:
      - "8080:80"
    depends_on:
      - event-service
      - booking-service
    networks:
      - my-events
