global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: eventservice
    static_configs:
      - targets: ["event-service:18181"]
  - job_name: bookingservice
    static_configs:
      - targets: ["booking-service:18282"]