---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-notifier

    receivers:
    - name: alert-notifier
      slack_configs:
      - send_resolved: true
        api_url: "https://hooks.slack.com/services/<my-slack-hook>"
        channel: "#hooks"
      