apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bookingservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        myevents/app: bookings
        myevents/tier: api
    spec:
      containers:
      - name: api
        image: maxsuelmarinho/my-events:booking-service-0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8282
          name: http
        env:
        - name: MONGO_URL
          value: mongodb://bookings-db/bookings
        - name: AMQP_BROKER_URL
          value: amqp://guest:guest@amqp-broker:5672/