concurrent = 3
log_level = "debug"

[[runners]]    
    url = "http://peon:30080"
    token = ""
    name = "autoscale-runner"
    executor = "docker+machine"
    limit = 5
    [runners.docker]
        image = "ubuntu:16.04"
        volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    [runners.machine]
        IdleCount = 2
        IdleTime = 120
        MachineName = "auto-scale-%s"