apiVersion: v1
kind: Pod
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: my-data
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: data
#  imagePullSecrets:
#  - name: my-private-registry-credentials